### ISSUE TITLE
Add a homepage video

### ISSUE THREAD

**Issue by aquibbaig** [zairza-cetb/club-website#25] opened 2019-04-20 04:23 UTC
Subject to debate: All modern websites have a slo-mo video on their background

Implementation: 
1. `https://rishabhp.github.io/bideo.js/`
2. `https://coverr.co/`
3. `http://vodkabears.github.io/vide/`

Whichever seems better!

**Comment by ankitjena** [comment] 2019-04-22 07:01
This can be done normally too. 
See https://stackoverflow.com/questions/36230522/adding-a-background-video-with-react

**Comment by aquibbaig** [comment] 2019-04-22 07:16
> This can be done normally too.
> See https://stackoverflow.com/questions/36230522/adding-a-background-video-with-react
> 
> To be checked what is better.

Take videos from those sites mentioned above!

**Comment by ganeshpatro321** [comment] 2019-04-22 08:09
Assign this to a second-year student. Give him resources.

**Comment by aquibbaig** [comment] 2019-04-22 12:35
@ganeshpatro321 Resources are above mentioned!

**Comment by initishh** [comment] 2019-04-23 12:31
I would like to work on this issue.

**Comment by alishamohanty** [comment] 2019-04-23 13:28
Sure @initishh. Could you share how you intend to make the home page through wireframes?  Discussions in #37 will help you to get started.

**Comment by initishh** [comment] 2019-04-23 15:16
For Wireframing, should I go for Adobe XD or any other tool?

**Comment by alishamohanty** [comment] 2019-04-23 15:26
Yeah, you can go for that, or you can try https://www.mockflow.com/ also.

**Comment by initishh** [comment] 2019-04-23 15:55
Thanks. I will update the progress here.

**Comment by ankitjena** [comment] 2019-04-24 08:59
@initishh Let's stick to what the issue is about. No need for home page wireframes.

**Comment by initishh** [comment] 2019-04-24 09:07
Okay, then I will just add a video to the homepage.

**Comment by agathver** [comment] 2019-04-28 15:04
My $0.02 here, Not convinced with videos, makes it impossible to load on mobiles and videos are in fact heavy for desktops too.

What you can actually opt is for CSS transitions (if you want to go that way)

**Comment by initishh** [comment] 2019-04-28 18:41
The image which is currently being used at https://zairza.netlify.com/ is of 1.4mb, while the video is of 780kb.  Also, the site is not lagging on using the video. Do have a check here. https://drive.google.com/file/d/1rUFFd61uShN7nTZ5gsIYVKz1GDONF7mK/view?usp=sharing

**Closed** 2019-05-01 10:01 UTC

**Comment by aquibbaig** [comment] 2019-05-10 06:49
Until we find a better video, @abhiMishra98 is designing an image. So I am reverting back to the old design. The image is subject to change after.
